version: '3.8'
services:
  frontend:
    image: front-end
    build: .
    container_name: simple-front-end
    ports:
      - 3000:5000
  backend:
    image: back-end
    build: .
    container_name: simple-back-end
    ports:
      - 7000:9000
    environment:
      - REDIS_HOST=redis-cache
  redis:
    image: redis
    build: .
    container_name: redis-cache
    ports:
      - 6379:6379
    command: redis-server --save 60 1
